//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.product = new HashSet<product>();
        }
    
        public int categoryid { get; set; }
        public string categoryname { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<product> product { get; set; }
    }
}
