//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pracrikceOffEntities : DbContext
    {
        public pracrikceOffEntities()
            : base("name=pracrikceOffEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> category { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<employee> employee { get; set; }
        public DbSet<employeerole> employeerole { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<orderitem> orderitem { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<supplier> supplier { get; set; }
        public DbSet<useraccount> useraccount { get; set; }
    }
}
