//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class orderitem
    {
        [Required]
        public int orderitemid { get; set; }
        [Required]
        public int orderid { get; set; }
        [Required]
        public int productid { get; set; }
        [Required]
        public int quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual product product { get; set; }
    }
}
