//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Order
    {
        public Order()
        {
            this.orderitem = new HashSet<orderitem>();
        }
    

        public int orderid { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Column(TypeName = "date")]
        public System.DateTime orderdate { get; set; }
        [Required]
        [StringLength(255)]
        public string deliveryaddress { get; set; }
        [Required]
        public string paymentmethod { get; set; }
        [Required]
        [Column(TypeName = "numeric(10, 2)")]
        [Range(0, int.MaxValue, ErrorMessage = "Общая цена должна быть неотрицательной!")]
        public decimal totalprice { get; set; }
        [Required]
        public string status { get; set; }
        public string comments { get; set; }
        [Required]
        public int customerid { get; set; }
        [Required]
        public int employeeid { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual employee employee { get; set; }
        public virtual ICollection<orderitem> orderitem { get; set; }
    }
}
