//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.orderitem = new HashSet<orderitem>();
        }
    
        public int productid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte[] image { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string status { get; set; }
        public string unitofmeasurement { get; set; }
        public int supplierid { get; set; }
        public int categoryid { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<orderitem> orderitem { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
