//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.product = new HashSet<product>();
        }
    
        public int supplierid { get; set; }
        public string name { get; set; }
        public string contactinfo { get; set; }
        public string location { get; set; }
        public string licensesandcertificates { get; set; }
        public string additionalcontactinfo { get; set; }
    
        public virtual ICollection<product> product { get; set; }
    }
}
