//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraccount
    {
        public int userid { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int roleid { get; set; }
        public int employeeid { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employeerole employeerole { get; set; }
    }
}
